# Starter pipeline
pool:
  vmImage: 'ubuntu-latest'

trigger:
- master

steps:
- task: CmdLine@2
  inputs:
    script: './Run.command -run -project_location "Projects/WebserviceDemoProject" -release "Azure" -testset "Get"'
    workingDirectory: '$(System.DefaultWorkingDirectory)/CITS'
   displayName: 'Execute CITS Test' 


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'Projects\WebserviceDemoProject\Results\TestExecution\Azure\Get\Latest\junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'API Test Run'
  displayName: 'Publish Reports'
