version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  automation:
    image: citsimage
    container_name: automation-test
    depends_on:
      - chrome 
    environment:
      - PROJ=Projects/DemoProject
      - RELEASE=Grid
      - TESTSET=Test
      - GRIDURL=http://selenium-hub:4444/wd/hub